liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix:   'media/cache'
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                  size: [330, 200]
                  mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800, 530]
                    mode: outbound
# driver: "gd"
# valid drivers options include "gd" or "gmagick" or "imagick"
# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html